use gpui::*;
actions!(
    glance,
    [
        Open,
        Save,
        ExportVideo,
        ExportGif,
        Spotlight,
        Magnifier,
        Copy,
        CopyRemote,
        CopyOcr,
        ChatgptAccount,
        AskGlance,
        Paste,
        Undo,
        Redo,
        Delete,
        Duplicate,
        SelectAll,
        Select,
        Pen,
        Arrow,
        Rectangle,
        Text,
        Highlight,
        Pixelate,
        Crop,
        Counter,
        CaptureArea,
        CaptureScreen,
        Fit,
        ActualSize,
        ZoomIn,
        ZoomOut,
        Backdrop,
        ImageTools,
        Help
    ]
);
pub fn install(cx: &mut App) {
    cx.bind_keys([
        KeyBinding::new(&crate::platform::key_binding("cmd-k"), AskGlance, None),
        KeyBinding::new(&crate::platform::key_binding("cmd-o"), Open, None),
        KeyBinding::new(&crate::platform::key_binding("cmd-s"), Save, None),
        KeyBinding::new(&crate::platform::key_binding("cmd-c"), Copy, None),
        KeyBinding::new(
            &crate::platform::key_binding("cmd-shift-c"),
            CopyRemote,
            None,
        ),
        KeyBinding::new(&crate::platform::key_binding("cmd-v"), Paste, None),
        KeyBinding::new(&crate::platform::key_binding("cmd-z"), Undo, None),
        KeyBinding::new(&crate::platform::key_binding("cmd-shift-z"), Redo, None),
        KeyBinding::new("backspace", Delete, None),
        KeyBinding::new(&crate::platform::key_binding("cmd-d"), Duplicate, None),
        KeyBinding::new(
            &crate::platform::key_binding("cmd-a"),
            SelectAll,
            Some("GlanceCanvas && !ColorPicker && !NumberInput && !AskPrompt"),
        ),
        KeyBinding::new(
            "v",
            Select,
            Some("GlanceCanvas && !ColorPicker && !NumberInput && !AskPrompt"),
        ),
        KeyBinding::new(
            "p",
            Pen,
            Some("GlanceCanvas && !ColorPicker && !NumberInput && !AskPrompt"),
        ),
        KeyBinding::new(
            "a",
            Arrow,
            Some("GlanceCanvas && !ColorPicker && !NumberInput && !AskPrompt"),
        ),
        KeyBinding::new(
            "r",
            Rectangle,
            Some("GlanceCanvas && !ColorPicker && !NumberInput && !AskPrompt"),
        ),
        KeyBinding::new(
            "t",
            Text,
            Some("GlanceCanvas && !ColorPicker && !NumberInput && !AskPrompt"),
        ),
        KeyBinding::new(
            "h",
            Highlight,
            Some("GlanceCanvas && !ColorPicker && !NumberInput && !AskPrompt"),
        ),
        KeyBinding::new(
            "b",
            Pixelate,
            Some("GlanceCanvas && !ColorPicker && !NumberInput && !AskPrompt"),
        ),
        KeyBinding::new(
            "x",
            Crop,
            Some("GlanceCanvas && !ColorPicker && !NumberInput && !AskPrompt"),
        ),
        KeyBinding::new(
            "n",
            Counter,
            Some("GlanceCanvas && !ColorPicker && !NumberInput && !AskPrompt"),
        ),
        KeyBinding::new(
            "s",
            Spotlight,
            Some("GlanceCanvas && !ColorPicker && !NumberInput && !AskPrompt"),
        ),
        KeyBinding::new(
            "m",
            Magnifier,
            Some("GlanceCanvas && !ColorPicker && !NumberInput && !AskPrompt"),
        ),
        KeyBinding::new(
            &crate::platform::key_binding("cmd-alt-2"),
            CaptureArea,
            None,
        ),
        KeyBinding::new(
            &crate::platform::key_binding("cmd-alt-3"),
            CaptureScreen,
            None,
        ),
        KeyBinding::new(&crate::platform::key_binding("cmd-1"), Fit, None),
        KeyBinding::new(&crate::platform::key_binding("cmd-0"), ActualSize, None),
        KeyBinding::new(&crate::platform::key_binding("cmd-="), ZoomIn, None),
        KeyBinding::new(&crate::platform::key_binding("cmd--"), ZoomOut, None),
    ]);
    cx.set_menus(vec![
        Menu {
            name: "Glance".into(),
            items: vec![
                MenuItem::action("ChatGPT account…", ChatgptAccount),
                MenuItem::action("Quit Glance", crate::Quit),
            ],
        },
        Menu {
            name: "File".into(),
            items: vec![
                MenuItem::action("Capture Area", CaptureArea),
                MenuItem::action("Capture Screen", CaptureScreen),
                MenuItem::separator(),
                MenuItem::action("Open Image…", Open),
                MenuItem::action("Save PNG…", Save),
                MenuItem::action("Export Backdrop Video…", ExportVideo),
                MenuItem::action("Export Looping GIF…", ExportGif),
            ],
        },
        Menu {
            name: "Edit".into(),
            items: vec![
                MenuItem::action("Undo", Undo),
                MenuItem::action("Redo", Redo),
                MenuItem::separator(),
                MenuItem::action("Copy", Copy),
                MenuItem::action("Copy (remote)", CopyRemote),
                MenuItem::action("Copy as OCR", CopyOcr),
                MenuItem::action("Ask Glance…", AskGlance),
                MenuItem::action("Paste", Paste),
                MenuItem::action("Delete", Delete),
                MenuItem::action("Duplicate", Duplicate),
                MenuItem::action("Select All", SelectAll),
            ],
        },
        Menu {
            name: "Draw".into(),
            items: vec![
                MenuItem::action("Select Objects", Select),
                MenuItem::separator(),
                MenuItem::action("Arrow", Arrow),
                MenuItem::action("Text", Text),
                MenuItem::action("Rectangle", Rectangle),
                MenuItem::action("Freehand Drawing", Pen),
                MenuItem::action("Highlighter", Highlight),
                MenuItem::action("Pixelate", Pixelate),
                MenuItem::action("Counter", Counter),
                MenuItem::action("Spotlight", Spotlight),
                MenuItem::action("Magnifier", Magnifier),
                MenuItem::separator(),
                MenuItem::action("Crop", Crop),
                MenuItem::action("Backdrop", Backdrop),
                MenuItem::action("Resize & Rotate", ImageTools),
            ],
        },
        Menu {
            name: "Zoom".into(),
            items: vec![
                MenuItem::action("Fit to Window", Fit),
                MenuItem::action("Actual Size", ActualSize),
                MenuItem::separator(),
                MenuItem::action("Zoom In", ZoomIn),
                MenuItem::action("Zoom Out", ZoomOut),
            ],
        },
        Menu {
            name: "Help".into(),
            items: vec![MenuItem::action("Glance Help", Help)],
        },
    ]);
}
